import type { Metadata } from "next";
import Link from "next/link";
import styles from "../legal.module.css";
export const metadata:Metadata={title:"Datenschutzerklärung | BahnConnections",description:"Datenschutzerklärung für BahnConnections Web, PWA und Android-App."};
export default function PrivacyPage(){return <main className={styles.page}><div className={styles.shell}><div className={styles.top}><Link className={styles.brand} href="/website">BahnConnections</Link><Link className={styles.back} href="/">Zur App</Link></div><article className={styles.card}>
<h1>Datenschutzerklärung</h1><p className={styles.meta}>Stand: 4. Oktober 2026 · Web-App, PWA und vorbereitete Android-App.</p>
<h2>1. Grundsatz</h2><p>Die öffentlichen Kernfunktionen von BahnConnections können ohne Online-Konto genutzt werden. BahnConnections ist ein unabhängiges Informationsangebot und keine offizielle App der Deutschen Bahn AG.</p>
<h2>2. Daten auf deinem Gerät</h2><p>Profilname, Heimatbahnhof, Favoriten, gespeicherte Pendelstrecken sowie Darstellungs- und Bedienpräferenzen werden im Browser-Speicher des Geräts abgelegt. Diese lokalen Daten werden nicht als Benutzerprofil an einen BahnConnections-Server synchronisiert. Das lokale Profil kann in den Einstellungen gelöscht werden; sämtliche lokalen Web-App-Daten lassen sich zusätzlich über die Website-/App-Daten des Browsers entfernen.</p>
<h2>3. Fahrplan- und Verbindungsabfragen</h2><p>Für Bahnhofstafeln, Reiseplanung und Fahrtdetails übermittelt die App die für die Abfrage notwendigen Angaben, etwa Haltestellen-IDs, Start, Ziel, Zeitpunkt und gewählte Filter, an BahnConnections-Serverfunktionen. Diese fragen externe Fahrplan- und Echtzeitdienste ab. Der Anwendungscode erstellt daraus kein persönliches Reiseprofil.</p>
<h2>4. Standort und Fußwege</h2><p>Der Gerätestandort wird nur nach ausdrücklicher Standortfreigabe verwendet. Er kann für die Kartenposition und – wenn du eine Fußwegfunktion startest – zur Berechnung des Weges zu einem Bahnhof genutzt werden. Für die Fußwegberechnung werden die benötigten Koordinaten an eine BahnConnections-Serverfunktion und von dort an Transitous/MOTIS übermittelt. Der Anwendungscode speichert diese Koordinaten nicht im Profil und legt daraus keinen Standortverlauf an. Die Standortfreigabe kann im Browser jederzeit entzogen werden.</p>
<h2>5. Externe Dienste</h2><ul><li>Transitous / MOTIS: Fahrplan-, Echtzeit- und Fußwegdaten.</li><li>transport.rest: zusätzliche Gegenprüfung ausgewählter Fahrplandaten.</li><li>OpenStreetMap und ausgewiesene Kartendienste: Karten- und Geodaten.</li></ul><p>Transitous gibt an, bei Nutzung seiner Website oder API insbesondere IP-Adresse, Zeitpunkt, angefragte URL und User-Agent in Logdateien zu speichern und diese Logs bis zu zwei Tage aufzubewahren. Die angefragte URL kann unter anderem Start und Ziel einer Route, Zeitpunkt, Verkehrsmittel, Suchanfragen oder Standortangaben enthalten. Bei über BahnConnections-Serverfunktionen weitergeleiteten Anfragen können die technisch sichtbaren Verbindungsdaten von der direkten Browsernutzung abweichen. Für die eigene Verarbeitung externer Anbieter gelten deren Bedingungen und Datenschutzhinweise.</p>
<h2>6. Technische Verbindungsdaten</h2><p>Beim Verbindungsaufbau wird technisch insbesondere die IP-Adresse an die beteiligte Hosting- und Netzwerkinfrastruktur übertragen. BahnConnections führt im Anwendungscode daraus kein eigenes Tracking- oder Werbeprofil. Es sind keine Werbe-SDKs eingebunden.</p>
<h2>7. Zahlungen</h2><p>In der derzeitigen öffentlichen Version werden keine Live-Zahlungen für digitale Funktionen angenommen. Stripe-Bausteine befinden sich ausschließlich in einer nicht freigeschalteten Test-/Sandbox-Vorbereitung. Digitale Abonnements in einer Play-Version werden erst mit einem Google-Play-konformen Zahlungsweg aktiviert.</p>
<h2>8. Löschung</h2><p>Gerätelokale Einstellungen bleiben gespeichert, bis du sie in der App oder im Browser löschst. Standortkoordinaten werden im Anwendungscode nicht als Standortverlauf gespeichert. Für die öffentlichen Kernfunktionen gibt es derzeit kein produktives serverseitiges Benutzerkonto.</p>
<h2>9. Sicherheit</h2><p>Die produktive Anwendung wird über HTTPS bereitgestellt. Sensible Schlüssel und Zahlungsgeheimnisse gehören nicht in Client-Code oder das öffentliche Repository.</p>
<h2>10. Kontakt und rechtliche Angaben</h2><p>Technische Datenschutz- und Supportanfragen können über <a href="https://github.com/Cola968/BahnConnections/issues" target="_blank" rel="noreferrer">BahnConnections Issues</a> gestellt werden. Vor einer kommerziellen Veröffentlichung müssen die vollständigen Angaben des rechtlich verantwortlichen Entwicklers und eine geeignete Kontaktmöglichkeit auf dieser Seite sowie in Google Play ergänzt und geprüft werden.</p>
<div className={styles.links}><Link href="/terms">Nutzungsbedingungen</Link><Link href="/support">Support</Link><Link href="/website">Website</Link></div></article></div></main>}