import assert from 'node:assert/strict';
import Stripe from 'stripe';
import {billingConfig,approvedSubscription,sameOrigin,verifiedEvent} from '../app/billing/core.ts';
import {parseSavedRoutes} from '../app/saved-routes.ts';
const env={BILLING_MODE:'test',STRIPE_SECRET_KEY:'rk_test_fixture',STRIPE_WEBHOOK_SECRET:'whsec_fixture',STRIPE_PRICE_MONTH:'price_month',STRIPE_PRICE_YEAR:'price_year',BILLING_ORIGIN:'https://bahnconnections.example',STRIPE_PORTAL_CONFIGURATION:'bpc_fixture'};
const config=billingConfig(env);assert.ok(config);
for(const patch of [{BILLING_MODE:'live'},{STRIPE_SECRET_KEY:'sk_live_fixture'},{STRIPE_WEBHOOK_SECRET:''},{STRIPE_PRICE_YEAR:''},{BILLING_ORIGIN:'https://bahnconnections.example/untrusted'},{BILLING_ORIGIN:'http://bahnconnections.example'}])assert.equal(billingConfig({...env,...patch}),null);
assert.equal(sameOrigin(new Request(env.BILLING_ORIGIN,{headers:{origin:env.BILLING_ORIGIN}}),config),true);
assert.equal(sameOrigin(new Request(env.BILLING_ORIGIN,{headers:{origin:'https://attacker.example'}}),config),false);
const subscription={livemode:false,status:'active',items:{data:[{quantity:1,price:{id:'price_month'},current_period_end:Math.floor(Date.now()/1000)+3600}]}};
assert.equal(approvedSubscription(subscription,config),true);
for(const status of ['past_due','unpaid','canceled','incomplete','incomplete_expired','paused','trialing'])assert.equal(approvedSubscription({...subscription,status},config),false);
assert.equal(approvedSubscription({...subscription,livemode:true},config),false);
for(const item of [{quantity:2,price:{id:'price_month'},current_period_end:1e12},{quantity:1,price:{id:'price_other'},current_period_end:1e12},{quantity:1,price:{id:'price_month'},current_period_end:1}])assert.equal(approvedSubscription({...subscription,items:{data:[item]}},config),false);
const raw=JSON.stringify({id:'evt_fixture',type:'customer.subscription.deleted',livemode:false,data:{object:{id:'sub_fixture'}}});
const signature=Stripe.webhooks.generateTestHeaderString({payload:raw,secret:config.webhookSecret});
assert.equal((await verifiedEvent(raw,signature,config)).id,'evt_fixture');
await assert.rejects(()=>verifiedEvent(raw+' ',signature,config));
await assert.rejects(()=>verifiedEvent(raw,'t=1,v1=invalid',config));
const a={id:'a',name:'A',lat:52,lon:13,country:'DE'},b={id:'b',name:'B',lat:48,lon:11,country:'DE'};
const routes=parseSavedRoutes([{from:a,to:b},{from:a,to:b},{from:b,to:a},{from:a,to:a},{from:{...a,lat:999},to:b},null]);
assert.equal(routes.length,2);assert.notEqual(routes[0].id,routes[1].id);
assert.deepEqual(parseSavedRoutes({plan:'plus'}),[]);
assert.equal(parseSavedRoutes(Array.from({length:30},(_,i)=>({from:{...a,id:String(i)},to:b}))).length,20);
console.log('Billing audit passed: sandbox-only config, origin checks, expiry/status/product entitlement boundaries, signed/tampered webhooks, validated bounded routes. No external Stripe payment executed.');
